name: "Validate and Deploy Terraform Code"

on:
  pull_request:
    branches:
      - dev
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Helper Script
        run: |
          cd helper_scripts
          python3 replace_placeholders.py

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init, Validate, and Plan
        run: |
          cd iac
          terraform init
          terraform validate
          terraform plan -out=terraform.plan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: iac/terraform.plan

  deployment:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: iac

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Apply AWS Resources
        run: |
          cd iac
          terraform apply -auto-approve terraform.plan